use anchor_lang::prelude::*;
use anchor_spl::token_interface::{self, Transfer};

use crate::error::ErrorCode;
use crate::{repay, Loan};

/// The 8-byte discriminator for the borrow instruction
/// Generated by Anchor as the first 8 bytes of BLAKE3("global:borrow")
pub const BORROW_DISCRIMINATOR: &[u8] = &[228, 253, 131, 202, 207, 116, 89, 18];

pub fn handler(ctx: Context<Loan>, borrow_amount: u64) -> Result<()> {
    require_gt!(borrow_amount, 0u64, ErrorCode::InvalidAmount);

    let signer_seeds: &[&[&[u8]]] = &[&[b"protocol".as_ref(), &[ctx.bumps.protocol]]];

    let cpi_accounts = Transfer {
        from: ctx.accounts.protocol_ata.to_account_info(),
        to: ctx.accounts.borrower_ata.to_account_info(),
        authority: ctx.accounts.protocol.to_account_info(),
    };

    let cpi_program = ctx.accounts.token_program.to_account_info();

    let cpi_ctx = CpiContext::new_with_signer(cpi_program, cpi_accounts, signer_seeds);
    token_interface::transfer(cpi_ctx, borrow_amount)?;

    // analyze the instructions to ensure a repay instruction exists
    repay::repay_hook(&ctx)?;

    Ok(())
}
